### ISSUE TITLE
wrong shebang replacement

### ISSUE THREAD

**Issue by carlodri** [conda-forge/igor-feedstock#1]
when installing on my system, the original shebang lines in the python scripts (`#!/usr/bin/env python`) are replaced with ones referring to a non-existing path `#!C:/Miniconda3x64/bin/python` instead of `#!C:/Miniconda3x64/python`.

@synapticarbors can you help me as to why this happens?

**Comment by synapticarbors** [comment]
I would guess this is some sort of auto-replacement built into conda that is linux specific, but is applying it on Windows as well. It may have something to do with the `noarch`. 

@conda-forge/help-python any ideas on this? This may be an upstream conda issue.

**Comment by djsutherland** [comment]
Yeah, `scripts` don't work on Windows with `noarch: python` with conda-build 2. IIRC it's fixed in conda-build 3.

Options are:
- Patch the source to use `entry_points` instead of `scripts`. You'd have to make a Python function that does what the script does, and add `build/entry_points` entries.
- Take away the `noarch: python` and rerender.
